name: Build binaries

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt install upx

    - name: Build
      run: make build_all

    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
