name: Build binaries

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt install upx

    - name: Build binaries
      run: make build_all
    
    - name: Build deb package
      run: make deb

    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
